# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0005_auto_20171116_0045'),
        ('booths', '0004_auto_20171118_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Shop Name')),
                ('reservation_time', models.DateTimeField(auto_now_add=True, verbose_name='Reservation Time')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='markets.Market', verbose_name='Market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedBooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Canceled')], default=0, verbose_name='Status')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_booths', to='booths.Booth', verbose_name='Booth')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_booths', to='reservations.Reservation', verbose_name='Reservation')),
            ],
        ),
    ]
