# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0004_auto_20171118_1256'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved_booth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_reservations', to='booths.Booth', verbose_name='Approved Booth'),
        ),
    ]
