# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_approved_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Canceled')], default=0, verbose_name='Status'),
        ),
    ]
