# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0005_auto_20171116_0045'),
        ('reservations', '0003_reservation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set([('user', 'market')]),
        ),
    ]
