# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('reservations', '0004_auto_20171125_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='products',
            field=models.ManyToManyField(related_name='reservations', to='products.Product', verbose_name='products'),
        ),
    ]
