# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_reservation_approved_booth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.IntegerField(choices=[(1, 'Credit Card'), (2, 'Bank Transfer')], verbose_name='Payment Method')),
                ('round', models.IntegerField(verbose_name='Round')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('receipt_image', models.ImageField(null=True, upload_to='receipt_images/%Y/%m/%d', verbose_name='Receipt Image')),
                ('verification_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, verbose_name='Verification Status')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Drafted'), (1, 'Deposited'), (2, 'Fully Paid')], default=0, verbose_name='Status')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_payment_infos', to='reservations.Reservation', verbose_name='Reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_payment_info', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='installment',
            name='rental_payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.RentalPaymentInfo', verbose_name='Rental Payment Info'),
        ),
    ]
