# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpaymentinfo',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_payment_info', to='reservations.Reservation', verbose_name='Reservation'),
        ),
    ]
