# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0003_auto_20171113_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(max_length=5, verbose_name='Booth Number')),
                ('rental_fee', models.IntegerField(verbose_name='Rental Fee')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market', verbose_name='Market')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='booth',
            unique_together=set([('market', 'booth_number')]),
        ),
    ]
