# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='rental_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rental Fee'),
        ),
    ]
