# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
                ('account_id', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=5)),
                ('branch', models.CharField(max_length=20)),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessors.Lessor')),
            ],
        ),
    ]
