# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
