# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_auto_20171112_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('BBL', 'Bangkok Bank'), ('BBC', 'Bangkok Bank of Commerce'), ('KTB', 'Krung Thai Bank'), ('BAY', 'Bank of Ayudhya'), ('KBANK', 'Kasikorn Bank'), ('CITI', 'Citi Bank'), ('TMB', 'TMB Bank'), ('SCB', 'The Siam Commercial Bank'), ('NBANK', 'Thanachart Bank'), ('SCIB', 'Siam City Bank'), ('GSB', 'Government Savings Bank'), ('GHB', 'Government Housing Bank')], max_length=5, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch',
            field=models.CharField(max_length=100, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='lessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessors.Lessor', verbose_name='Lessor'),
        ),
    ]