sudo: false
dist: trusty
language: node_js
node_js:
  - "8.4.0"

notifications:
  slack:
    secure: CW+HTTRGL/zYkune4nL+k5ZwkFe9aeoHMFMjRkKaROk2u9hP/swz714N7X++v+3PpevdboDttGUajMmWtiKLIH+T+l8NBOsLgqVaFGlg0CFRirAQmw/xUtqvBkQQXtHgPq8DuBekRQhNiBkL0uWJvRw4SvNuso5l9/MDLE3sS6TlAHyiMRz2b1P9ydhZseJJ3ATFpLyAvvADd+rvJnIFgcL3rgS8hXjhU3AHmXDUg+XLwjQfawGWa6xB0cckn6Kdc8dsZ3DiETWTSdu4ihtIh3xU9cv6NhfWSXasxaleBQkuTwECirG9E7+WBHDvPtNsXauPJCOEB8VT0597eJQG/I4HbX8X3Gq/VYudz9aHCc7Qs6AnleowgKA6PxAFesliniX8/fW0fvrDHzrXK+ro5GraUTkg7ifX9hcz76NrlulA5ZIBr7NvD0eVsaocbED88Qz0nwBYL/6RZQhaCCNWSbUceMeImm7wkcudSl0nZDxx5xfjBqRc92Uzq0uO+wJs6T7VWC/5uv2u6iyJVId1rUPqquig4j9LuXSYbU1zJua2u+Jdbo8uvpupGele7Rw1tVVrKpJzXYG/Do4+nh3amWl7cthT1XsPuQFUxoNc1q+8ryAVSAf5ADxKJ2w0iGdlPDgHPTZ2XTSHsPuBgcEbjHAHPnjfpAWPopz0+sRilGU=

cache:
  yarn: true
  directories:
    - ./frontend-webapp/node_modules

before_install:
  # Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH=$HOME/.yarn/bin:$PATH
  # Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  # Docker Compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.11.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - cd $TRAVIS_BUILD_DIR/frontend-webapp
  - yarn install
  - cd $TRAVIS_BUILD_DIR/webserver
  - docker-compose up --build -d

script:
  - cd $TRAVIS_BUILD_DIR/frontend-webapp
  - yarn test --single-run --no-progress --browser=ChromeHeadless
  - ../scripts/loop-ping-server.sh && yarn e2e --no-progress --config=protractor-ci.conf.js
  - yarn lint
