version: '3'

services:
  db:
    image: postgres
    container_name: mms-postgres
  web:
    build: .
    command: python3 ./webserver/manage.py runserver 0.0.0.0:8000
    container_name: mms-webserver
    volumes:
      - .:/webserver
    ports:
      - "8000:8000"
    depends_on:
      - db