version: '3'

services:
  db:
    image: postgres
    container_name: mms-postgres
    ports:
      - "5432:5432"
    # environment:
    #     - POSTGRES_PASSWORD=password                                                    
    #     - POSTGRES_USER=username
    #     - POSTGRES_DB=postgres
    #     - PGDATA=/data/postgres
    volumes:
        - ./data/postgres:/data/postgres

  pgadmin:
    image: fenglc/pgadmin4
    links:
      - db:postgres
    container_name: mms-pgadmin
    volumes:
       - ./data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    restart: unless-stopped

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: mms-webserver
    volumes:
      - ./webserver:/webserver
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    
