version: '3'

services:
  db:
    image: postgres
    ports:
      - "54321:5432"
    volumes:
        - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: fenglc/pgadmin4
    links:
      - db:postgres
    volumes:
       - ./data/pgadmin:/var/lib/pgadmin4
    ports:
      - "5050:5050"
    restart: unless-stopped

  webserver:
    build: ./webserver
    volumes:
      - ./webserver:/webserver
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:postgres

  frontend_webapp:
    build: ./frontend-webapp
    volumes:
      - ./frontend-webapp/e2e:/frontend-webapp/e2e
      - ./frontend-webapp/src:/frontend-webapp/src
    ports:
      - "4200:4200"
    depends_on:
      - webserver
    links:
      - webserver:api
