# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 19:45
from __future__ import unicode_literals

import apps.commons.file_upload
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.NullBooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('money_transfer_to_lessor_status', models.IntegerField(choices=[(0, 'Not Transferred'), (1, 'In Progress'), (2, 'Complete'), (3, 'Cancelled')], default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Market Name')),
                ('caption', models.TextField(verbose_name='Market Caption')),
                ('description', models.TextField(verbose_name='Market Description')),
                ('opening_date', models.DateTimeField(verbose_name='Opening Date')),
                ('closing_date', models.DateTimeField(verbose_name='Closing Date')),
                ('opening_time', models.TimeField(verbose_name='Opening Time')),
                ('closing_time', models.TimeField(verbose_name='Closing Time')),
                ('contact_person_fullname', models.CharField(max_length=100, verbose_name='Contact Person Fullname')),
                ('contact_person_phone_number', models.CharField(max_length=20, verbose_name='Contact Person Phone Number')),
                ('contact_person_email', models.EmailField(max_length=254, verbose_name='Contact Person Email')),
                ('location', models.CharField(max_length=200, verbose_name='location')),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('term_and_condition', models.TextField(max_length=1000, verbose_name='Terms and Conditions')),
                ('deposit_payment_due', models.DateTimeField(verbose_name='Deposit Due Date')),
                ('full_payment_due', models.DateTimeField(verbose_name='Full Payment Due Date')),
                ('reservation_due_date', models.DateTimeField(verbose_name='Reservation Due Date')),
                ('estimate_visitor', models.IntegerField(blank=True, null=True, verbose_name='Estimated Visitors')),
                ('min_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, verbose_name='Maximum Price')),
                ('layout_photo', models.ImageField(upload_to='cover_photos/%Y/%m/%d', verbose_name='Layout Image')),
                ('provided_accessories', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Provided Accessories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_image', models.ImageField(upload_to='cover_photos/%Y/%m/%d', verbose_name='Scene_Image')),
            ],
        ),
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('image', models.ImageField(upload_to=apps.commons.file_upload.random_filename, verbose_name='Uploaded Image')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Thumb Nail')),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='markets.Market')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market'),
        ),
        migrations.AddField(
            model_name='market',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='market',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
