# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverphoto',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='markets.Market'),
        ),
    ]
