# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20171113_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverphoto',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cover_photo', serialize=False, to='markets.Market'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_photos', to='markets.Market'),
        ),
    ]
