# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_auto_20171113_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverphoto',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cover_photo', serialize=False, to='markets.Market'),
        ),
    ]
