# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_auto_20171114_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='scene_image',
            field=models.ImageField(upload_to='scene_photo/%Y/%m/%d', verbose_name='Scene Image'),
        ),
    ]
