# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20171116_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_approved_all_reservations',
            field=models.BooleanField(default=False, verbose_name='Is approved all reservations'),
        ),
    ]
