# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:08
from __future__ import unicode_literals

import apps.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Product Name')),
                ('description', models.CharField(max_length=254, verbose_name='Product Description')),
                ('image', models.ImageField(upload_to=apps.products.models.random_filename, verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
