# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_facebook_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessor',
            fields=[
                ('lessor_name', models.CharField(max_length=100, verbose_name='Lessor Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
