# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0002_auto_20171113_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessor',
            name='is_organization',
            field=models.BooleanField(default=False, verbose_name='Is Organization'),
        ),
        migrations.AddField(
            model_name='lessor',
            name='organization_contact_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Organization Contact Name'),
        ),
        migrations.AddField(
            model_name='lessor',
            name='organization_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Organization Email'),
        ),
        migrations.AddField(
            model_name='lessor',
            name='organization_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='lessor',
            name='organization_phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Organization Phone Number'),
        ),
    ]
