# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0003_auto_20171114_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessor',
            name='organization_contact_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Organization Contact Name'),
        ),
        migrations.AlterField(
            model_name='lessor',
            name='organization_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Organization Email'),
        ),
        migrations.AlterField(
            model_name='lessor',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='lessor',
            name='organization_phone_number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Organization Phone Number'),
        ),
    ]
