# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Tag')),
                ('market', models.ManyToManyField(to='markets.Market')),
            ],
        ),
    ]
