# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='market',
            field=models.ManyToManyField(related_name='tags', to='markets.Market'),
        ),
    ]
