# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0005_auto_20171116_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.CharField(max_length=500, verbose_name='Report Content')),
                ('time_stamp', models.DateTimeField(verbose_name='Time Stamp')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market', verbose_name='Market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
