# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook Token'),
        ),
    ]
