# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_facebook_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_token',
            field=models.TextField(blank=True, max_length=255, verbose_name='Facebook Token'),
        ),
    ]
