# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171112_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='Card Number')),
                ('card_holder_name', models.CharField(max_length=50, verbose_name='Card Holder Name')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'MasterCard'), (2, 'Visa')])),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('verification_no', models.CharField(max_length=10, verbose_name='Verification Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
