# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171113_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='Card Number')),
                ('card_holder_name', models.CharField(max_length=50, verbose_name='Card Holder Name')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'MasterCard'), (2, 'Visa')])),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('verification_no', models.CharField(max_length=10, verbose_name='Verification Number')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_token',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Facebook Token'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
