# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171114_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='facebook_token',
            new_name='facebook_id',
        ),
    ]
