# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171117_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiry_month',
            field=models.CharField(default='01', max_length=2, verbose_name='Expiry Month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiry_year',
            field=models.CharField(default='17', max_length=2, verbose_name='Expiry Year'),
            preserve_default=False,
        ),
    ]
