# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='Card Number')),
                ('card_holder_name', models.CharField(max_length=50, verbose_name='Card Holder Name')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'MasterCard'), (2, 'Visa')])),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('verification_no', models.CharField(max_length=10, verbose_name='Verification Number')),
            ],
        ),
    ]
