# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booths', '0004_auto_20171118_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Shop Name')),
                ('reservation_time', models.DateTimeField(auto_now_add=True, verbose_name='Reservation Time')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Canceled')], default=0, verbose_name='Status')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booths.Booth', verbose_name='Booth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
