# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreservation',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_reservations', to='booths.Booth', verbose_name='Booth'),
        ),
        migrations.AlterField(
            model_name='marketreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_reservations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
